# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container:
    runs-on: ubuntu-20.04
    #container: itisfoundation/puppeteer:14-2 #FIXME
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Print Public IP
        run: |
          echo 'ipv4: ${{ steps.ip.outputs.ipv4 }}'
          echo 'ipv6: ${{ steps.ip.outputs.ipv6 }}'
      - run: ./generate-certificates.sh
        env:
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
      - run: ./install-frp.sh
      - name: run frpc
        run: ./run-frpc.sh
        env:
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
